# Generated by Django 4.1.6 on 2023-02-10 02:45

from django.db import migrations

def transfer_date(apps, schema_editor):
    Photo = apps.get_model('main_app', 'Photo')
    PhotoContext = apps.get_model('main_app', 'PhotoContext')
    for photocontext in PhotoContext.objects.all():
        photocontext.date_link = photocontext.date
        photocontext.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photocontext_date_link'),
    ]

    operations = [
        migrations.RunPython(transfer_date)
    ]
