# Generated by Django 4.1.6 on 2023-02-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_photocontext_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photocontext',
            old_name='date_link',
            new_name='date',
        ),
    ]
